frutas=["mango", "limon"]
print(frutas)
print(frutas)
print(frutas[1])
print(len(frutas))
frutas.append("fresas")
print(frutas)
frutas.append("zarza")
print(frutas)
frutas.sort()
print(frutas)
porcomprar=input("ingresa una fruta: ")
frutas.append(porcomprar)
print(frutas)